version: "2.1"
orbs:
  qodana: jetbrains/qodana@2025.2

jobs:
  code-quality:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Optional: restore node cache if you add package.json later
      - qodana/scan:
          args: "--cache-dir ~/.cache/qodana"

workflows:
  main:
    jobs:
      - code-quality