version: 2.1

jobs:
  code-quality:
    docker:
      - image: jetbrains/qodana-jvm:latest
    steps:
      - checkout
      - run:
          name: Run Qodana Scan
          command: qodana scan --fail-threshold 1

workflows:
  main:
    jobs:
      - code-quality
